=== rakshittonmoy/GeoGnosis/app/schema/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
      "type": "object",
      "properties": {
        "_id": {
          "type": "string"
        },
        "place": {
          "type": "string"
        },
        "timestamp": {
          "type": "string",
          "format": "date-time"
        },
        "attractions": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "lat": {
                "type": "number"
              },
              "lon": {
                "type": "number"
              },
              "name": {
                "type": "string"
              }
            },
            "required": ["lat", "lon", "name"]
          }
        }
      },
      "required": ["_id", "place", "timestamp", "attractions"]
    }
  }

=== rakshittonmoy/GeoGnosis/app/queries/recentlySearchedAttractions.json
[
    {
        "_id": "66645c1e1a9f91af55dd12a1",
        "attractions": [
            {
                "lat": 41.8785046,
                "lon": -87.6358868,
                "name": "SkyDeck Chicago Willis Tower"
            },
            {
                "lat": 41.8805793,
                "lon": -87.6304123,
                "name": "Weather Bell"
            },
            {
                "lat": 41.8912454,
                "lon": -87.6075786,
                "name": "The Wave Wall"
            },
            {
                "lat": 41.8796145,
                "lon": -87.6246298,
                "name": "Begin Route 66"
            },
            {
                "lat": 41.85296,
                "lon": -87.7097748,
                "name": "Gallager"
            },
            {
                "lat": 41.799589,
                "lon": -87.5916853,
                "name": "Obama Kissing Rock"
            },
            {
                "lat": 41.7866076,
                "lon": -87.5833157,
                "name": "Japanese Garden"
            },
            {
                "lat": 41.9229477,
                "lon": -87.6339882,
                "name": "Dwarf Crocodile"
            },
            {
                "lat": 41.9232763,
                "lon": -87.6340967,
                "name": "Klipspringer"
            },
            {
                "lat": 41.867919,
                "lon": -87.6130245,
                "name": "Dolphin"
            },
            {
                "lat": 41.8673317,
                "lon": -87.6130031,
                "name": "Beluga"
            },
            {
                "lat": 41.8674176,
                "lon": -87.6132257,
                "name": "Sea Lion"
            },
            {
                "lat": 41.8678633,
                "lon": -87.6132034,
                "name": "Sea Otter"
            },
            {
                "lat": 41.8675992,
                "lon": -87.6132033,
                "name": "Penguins"
            },
            {
                "lat": 41.7906648,
                "lon": -87.58242,
                "name": "Flight and Motion Simulators"
            },
            {
                "lat": 41.7910108,
                "lon": -87.5829457,
                "name": "YOU! The Experience"
            },
            {
                "lat": 41.8856307,
                "lon": -87.6983895,
                "name": "Waller Apartments"
            },
            {
                "lat": 41.7912809,
                "lon": -87.581293,
                "name": "U-505 Submarine"
            },
            {
                "lat": 41.8934261,
                "lon": -87.6263927,
                "name": "The Escape Game Chicago"
            },
            {
                "lat": 41.7916454,
                "lon": -87.5829488,
                "name": "Pioneer Zephyr"
            },
            {
                "lat": 41.8788896,
                "lon": -87.6363229,
                "name": "The Ledge"
            },
            {
                "lat": 41.9433238,
                "lon": -87.6768788,
                "name": "Chicago Rat Hole"
            },
            {
                "lat": 41.8523211,
                "lon": -87.7200512,
                "name": "Castle Car Wash"
            }
        ],
        "place": "chicago",
        "timestamp": "Thu, 20 Jun 2024 12:09:23 GMT"
    },
    {
        "_id": "6672af5b54694821a61c198a",
        "attractions": [
            {
                "lat": 52.3701984,
                "lon": 4.892168,
                "name": "The Amsterdam Dungeon"
            },
            {
                "lat": 52.3448864,
                "lon": 4.8561555,
                "name": "Olympiahuis"
            },
            {
                "lat": 52.3128478,
                "lon": 4.8244491,
                "name": "Geitenboerderij Ridammerhoeve"
            },
            {
                "lat": 52.3702214,
                "lon": 4.8995216,
                "name": "Zuiderkerkstoren"
            },
            {
                "lat": 52.368622,
                "lon": 4.9011934,
                "name": "Waterloopleinmarkt"
            },
            {
                "lat": 52.3691145,
                "lon": 4.8897114,
                "name": "Houten Huis"
            },
            {
                "lat": 52.365606,
                "lon": 4.8915478,
                "name": "Kattenkabinet"
            },
            {
                "lat": 52.3618254,
                "lon": 4.8826864,
                "name": "Blue Boat"
            },
            {
                "lat": 52.3902323,
                "lon": 4.8538505,
                "name": "Blast Galaxy"
            },
            {
                "lat": 52.3861071,
                "lon": 4.8721438,
                "name": "Fabrique des Lumi\u00e8res"
            },
            {
                "lat": 52.3776269,
                "lon": 4.9163299,
                "name": "IJ-toren"
            },
            {
                "lat": 52.3695598,
                "lon": 4.9040064,
                "name": "Gassan Diamonds"
            },
            {
                "lat": 52.3702059,
                "lon": 4.8919252,
                "name": "Nieuwzijds Kapel"
            },
            {
                "lat": 52.3712304,
                "lon": 4.8977104,
                "name": "Walenpoortje"
            },
            {
                "lat": 52.3636914,
                "lon": 4.8808218,
                "name": "Lovers canal Cruises"
            },
            {
                "lat": 52.3582092,
                "lon": 4.8914313,
                "name": "Amsterdam canal cruises"
            },
            {
                "lat": 52.3674542,
                "lon": 4.8862097,
                "name": "The Fault In Our Stars Bench"
            },
            {
                "lat": 52.3764135,
                "lon": 4.8981659,
                "name": "Stromma Open Boat Tours"
            },
            {
                "lat": 52.3763021,
                "lon": 4.8980264,
                "name": "Stromma NL"
            },
            {
                "lat": 52.3761892,
                "lon": 4.8978708,
                "name": "Stromma NL"
            },
            {
                "lat": 52.3757651,
                "lon": 4.8971842,
                "name": "Rederij Plas"
            },
            {
                "lat": 52.3671687,
                "lon": 4.895146,
                "name": "Rondvaart Canal"
            },
            {
                "lat": 52.3692824,
                "lon": 4.8951018,
                "name": "Gasthuispoort"
            },
            {
                "lat": 52.3618668,
                "lon": 4.8825953,
                "name": "Blue Boat"
            },
            {
                "lat": 52.3710168,
                "lon": 4.9120281,
                "name": "Glow Golf"
            },
            {
                "lat": 52.3761472,
                "lon": 4.8999848,
                "name": "Sint Olofskapel"
            },
            {
                "lat": 52.3693921,
                "lon": 4.8946812,
                "name": "Huis aan 3 grachten"
            },
            {
                "lat": 52.3709981,
                "lon": 4.8980255,
                "name": "Oost-Indisch Huis"
            },
            {
                "lat": 52.3786758,
                "lon": 4.8971651,
                "name": "Canal Cruise"
            },
            {
                "lat": 52.365077,
                "lon": 4.884086,
                "name": "Amsterdam Hop on Hop Off"
            },
            {
                "lat": 52.3842002,
                "lon": 4.902329,
                "name": "This is Holland"
            },
            {
                "lat": 52.3691622,
                "lon": 4.8923587,
                "name": "Ruiterstandbeeld van Koningin Wilhelmina"
            },
            {
                "lat": 52.3635339,
                "lon": 4.880547,
                "name": "Canal Cruise"
            },
            {
                "lat": 52.3837971,
                "lon": 4.9022681,
                "name": "Over The Edge"
            },
            {
                "lat": 52.3191242,
                "lon": 4.9062529,
                "name": "Rembrandt Hoeve"
            },
            {
                "lat": 52.3773046,
                "lon": 4.8990559,
                "name": "Stromma"
            },
            {
                "lat": 52.3776829,
                "lon": 4.8995626,
                "name": "Rederij Kooij"
            },
            {
                "lat": 52.3789395,
                "lon": 4.8974418,
                "name": "Lovers Canal cruises/ Hop on Hop Off"
            },
            {
                "lat": 52.3769495,
                "lon": 4.8998343,
                "name": "Stromma"
            },
            {
                "lat": 52.3738217,
                "lon": 4.8973988,
                "name": "The red lights street"
            },
            {
                "lat": 52.4012778,
                "lon": 4.8965946,
                "name": "IJ-Hallen"
            },
            {
                "lat": 52.3789335,
                "lon": 4.8974548,
                "name": "Stromma Hop on Hop off"
            },
            {
                "lat": 52.3705173,
                "lon": 4.896312,
                "name": "Spinhuispoort"
            },
            {
                "lat": 52.368997,
                "lon": 4.8925464,
                "name": "Rederij Kooij"
            },
            {
                "lat": 52.3899596,
                "lon": 4.9385813,
                "name": "Beeldenbos Noord"
            },
            {
                "lat": 52.4368833,
                "lon": 4.8240113,
                "name": "House painted by Monet in 1871"
            },
